#!/usr/bin/env sh

# set up config
export XDG_CONFIG_HOME="$HOME/.conf"
export XDG_CACHE_HOME="$HOME/.cache"

# install brew
echo 'installing homebrew...'
ruby -e `curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install`

# install homerun things
sh "$XDG_CONFIG_HOME/homerun/lib/install"

# intialize cache dir
mkdir "$XDG_CACHE_HOME"

# QUICKLOOK PLUGINS
# adds colors to quicklook preview
brew cask install qlcolorcode

# add ql support for files w/o extension
brew cask install qlstephen

# add markdown support
brew cask install qlmarkdown

# add webp support
brew cask install webpquicklook

# shows image dimension and size in title
brew cask install qlimagesize


# SIMBL
brew cask install easysimbl

# MouseTerm: https://bitheap.org/mouseterm/

# vim: ft=zsh
