#!/bin/env sh

# install neovim with brew
brew tap neovim/neovim
brew install --HEAD neovim

vimdir="${PWD}/config"

mkdir -p  "$vimdir/bundle"
git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim

# set up cache folders
mkdir -p ./cache/nvim/{backup,swap,undo}

# vim: ft=zsh
