#!/bin/env sh

# install neovim with brew
brew tap neovim/neovim
brew install --HEAD neovim

vimdir="${PWD}/vimfiles"

# set up cache folders
mkdir -p $XDG_CACHE_HOME/nvim/{backup,swap,undo}

# vim: ft=zsh
