" VIMRC
" author: Romeo Van Snick
" e-mail: romeovs@gmail.com

" disable compatible mode
set nocompatible

let $VIM_HOME = expand("$XDG_CONFIG_HOME/vim/vimfiles")

let g:python2_host_prog = '/usr/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'

" set correct vimdir
set runtimepath+=$VIM_HOME

" plugins <<
call plug#begin(expand('$VIM_HOME/bundle/'))

Plug 'shougo/vimproc.vim', { 'do': 'make' }

Plug 'tpope/vim-surround'         " mappings to work with ' ( etc
Plug 'tpope/vim-repeat'           " repeat more stuff
Plug 'vim-scripts/matchit.zip'         " better matching with %
Plug 'godlygeek/tabular'          " table alignment
Plug 'terryma/vim-expand-region'  " handy expansion of region

" >>

" filetype plugins <<
" golang
Plug 'fatih/vim-go'
let g:auto_type_info = 1
" let g:go_fmt_experimental = 1
let g:go_template_autocreate = 0

" haskell
Plug 'eagletmt/ghcmod-vim', { 'for': 'haskell' }
Plug 'eagletmt/neco-ghc',   { 'for': 'haskell' }

" html
Plug 'othree/html5.vim'
Plug 'rstacruz/sparkup',    { 'for': [ 'html', 'javascript' ] }

" js
" Plug 'jsx/jsx'
" Plug 'othree/yajs.vim'
" Plug 'othree/es.next.syntax.vim'
" Plug 'othree/xml.vim'
Plug 'pangloss/vim-javascript'
" Plug 'mxw/vim-jsx'
let g:jsx_ext_required = 0

" css
Plug 'JulesWang/css.vim'
Plug 'hhsnopek/vim-sugarss'
" Plug 'romeovs/vim-stylus'
Plug 'aisapatino/vim-stylus'

" handlebars
Plug 'mustache/vim-mustache-handlebars'

" applescript
Plug 'vim-scripts/applescript.vim'

" markdown
Plug 'tpope/vim-markdown'
let g:vim_markdown_frontmatter=1
let g:vim_markdown_folding_disabled=1

" nginx
Plug 'evanmiller/nginx-vim-syntax'

" octave
Plug 'vim-scripts/octave.vim'

" >>

" fix timeouts <<
set timeout
set timeoutlen=750
set timeoutlen=500
" >>

" colors <<
syntax on                  " enable syntax highlighting
filetype plugin indent on  " enable filetyp and indentation
colorscheme custom         " color schme
set cursorline             " highlight cursor line
set number                 " enable linenumbers
" >>

" indentation <<
set softtabstop=0 " don't use soft tabstops
set tabstop=2     " width of tab character
set shiftwidth=2  " > > moves 4 spaces
set shiftround    " > and < round to shiftwidth
set expandtab     " expand tabs to spaces
set smarttab      " backspace over expand tabs
set noautoindent  " don't autoindent
set smartindent   " do use smartindent
set nocindent     " no strict indentation
" >>

" listchars <<
" set listchars to only show tabs and trailing whitespace
exec "set listchars=trail:\uB7,nbsp:_,tab:\uBB\\ "
set list
" >>

" wrapping <<
set textwidth=80        " wrap to 80
set formatoptions-=t    " don't wrap automatically
set nowrap              " no line wrapping
" >>

" search <<
set incsearch   " search is incremental
set wrapscan    " wrap search
set nohlsearch  " don't highlight matches in search
set ignorecase  " ignore case in search
" >>

" drawing and shell <<
set vb t_vb=            " disable visual bells
set mouse=n             " enable mouse in normal mode
" >>

" conceal and fill <<
set conceallevel=0      " don't conceal chars
set fillchars=fold:\ ,stl:\ ,stlnc:\ ,vert:\|
" >>

" file handling <<
set encoding=utf-8  " set file encoding
set autoread        " auto read the file if it was modified
set autochdir       " automatically change to dir of file
set suffixes=.log,.aux,.out,,.pdf,.o,.hi
" >>

" text handling <<
set backspace=eol,start,indent " allow to backspace over these characters
set nrformats+=alpha           " also add/subtract alphabet
set cpo+=J                     " two space after sentence
" >>

" windows <<
set scrolloff=8         " set 8 lines of padding top/bottom while scrolling
set equalalways         " make splits equal
" >>

" swap <<
set undodir=$XDG_CACHE_HOME/nvim/undo
set undofile

set noswapfile
set directory=$XDG_CACHE_HOME/nvim/swap

set backup
set nowritebackup
set backupdir=$XDG_CACHE_HOME/nvim/backup

let g:netrw_home=expand('$XDG_CACHE_HOME/nvim')
set viminfo='100,n$XDG_CACHE_HOME/nvim/viminfo  " viminfo location
" >>

" folding <<
" sets the fold text
function! FoldText()
  let nl   = v:foldend + v:foldstart + 1
  let text = substitute(getline(v:foldstart), "^ *", "", "")
  let text = substitute(text, "{{{", "", 1) " }}}
  let text = substitute(text, split(&cms, "%s")[0], "", "")
  let text = substitute(text, split(&cms, "%s")[1], "", "")
  let text = substitute(text, "^ ", "", "")
  let lvl  = substitute(v:folddashes, "-", "·", "g")
  let fill = repeat(' ', (winwidth(0) - strlen(lvl . " " .  text . "(". nl ." lines)")-9))
  let foldtext = " " . text . " " .lvl . fill . "(" . nl . " lines)"
  return foldtext
endfunction
set foldcolumn=2
set foldtext=FoldText()
" >>

" map keys <<
let mapleader = "\<space>"

imap § <esc>
vmap § <esc>
cmap § <esc>

" escape with jkl
imap jkl <esc>

" toggle folds with space
nnoremap <Leader><Leader> za
" nnoremap <space> <nop>

" better save
nnoremap <Leader>w :w<cr>
nnoremap - :w<cr>

" better quit
nnoremap Q  :q<cr>
nnoremap q: :q<cr>

" region expansion
vmap K <Plug>(expand_region_expand)
vmap J <Plug>(expand_region_shrink)
nnoremap J <NOP>
nnoremap K v

" tabs
nmap t :tabnew<space>
nmap <silent> <tab>   :tabnext<cr>
nmap <silent> <S-tab> :tabprev<cr>

nmap <silent> <M-tab> :wincmd w<cr>


" commandline begin and end
cno <C-a> <Home>
cno <C-e> <End>

inoremap <C-a> <NOP>
inoremap <C-e> <NOP>

" paste / copy from system
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P

nnoremap <cr> G
nnoremap <bs> gg

" bubble lines
Plug 'tpope/vim-unimpaired'

nmap <silent> <up> [e
nmap <silent> <down> ]e
vmap <silent> <up>   [egv
vmap <silent> <down> ]egv

" quick indent with arrow keys
nnoremap <left>  <<
nnoremap <right> >>

vnoremap <left>  <gv
vnoremap <right> >gv

vnoremap < <gv
vnoremap > >gv

" terminal mappings
tnoremap <esc> <C-\><C-n>
tnoremap <C-w> <C-\><C-n>

" >>

" comments <<
Plug 'tomtom/tcomment_vim'

" add comment types
au FileType php   set commentstring=<!--\ %s\ -->
au FileType agda  set commentstring=--\ %s
au FileType idris set commentstring=--\ %s
au FileType jsx   set commentstring=//\ %s

" map keys
nmap       <silent> '  :TComment<CR>
vmap       <silent> '  :TComment<CR>

" >>

" statusline and commandline <<
Plug 'bling/vim-airline'

set showcmd       " show command being typed
set shortmess=a   " truncate messages
set cmdheight=2   " set the command line height to 2 lines
set noshowmode    " don't show mode
set laststatus=2

let g:airline_theme='custom'

let g:airline_symbols   = {}
let g:airline_left_sep  = ''
let g:airline_right_sep = ''
let g:airline_section_warning = ' '
let g:airline_powerline_fonts = 1
let g:airline_section_b = '%f%m'
function! AirlineInit()
  let g:airline_section_c = airline#section#create(['filetype'])
endfunction
autocmd User AirlineAfterInit call AirlineInit()
let g:airline_section_x = 'u%04b 0x%04B'
" >>

" show syntax stack <<
function! SynStack()
    if !exists('*synstack')
        return
    endif
    echo map(synstack(line('.'), col('.')), "synIDattr(v:val, 'name')")
endfunc
" >>

" editor config <<
Plug 'vim-scripts/PreserveNoEOL'      " for editorconfig
Plug 'editorconfig/editorconfig-vim'  " editorconfig
let g:EditorConfig_verbose = 0
let g:EditorConfig_exec_path = '/usr/local/bin/editorconfig'
" >>

" templates <<
Plug 'aperezdc/vim-template' " templates
let g:templates_name_prefix = 'default'
let g:templates_global_name_prefix = 'default'
let g:templates_directory = "$VIM_HOME/templates"

let g:templates_user_variables = [
  \ ['REACT_COMPONENT', 'GetReactComponent']
  \ ]

function! GetReactComponent()
  let l:file = expand('%:r:t')
  if l:file == 'index'
    let l:dir = expand('%:p:h:t')
    let l:name = l:dir
  else
    let l:name = l:file
  endif
  let l:ret = substitute(l:name, '^\(.\)', '\u\1', 'g')
  let l:ret = substitute(l:ret,  '[-_ ]\(.\)', '\u\1','g')
  return l:ret
endfunction

" >>

" spell <<
let g:myLang = 0
let g:myLangList = [ "nospell", "nl", "en_us" ]
function! MySpellLang()
  "loop through languages
  let g:myLang = g:myLang + 1
  if g:myLang >= len(g:myLangList) | let g:myLang = 0 | endif

  let l:lang   = g:myLangList[g:myLang]
  let l:simple = split(l:lang, '_')[0]

  if l:lang == "nospell"
    set nospell
    echo "spell off"
  else
    exec "setlocal spell spelllang=" . l:lang
    exec "setlocal spellfile=" . expand("$VIM_HOME/spell/") . l:simple . "." . &encoding . ".add"
    echo "spell language" l:lang
  endif

endf

map <F7> :call MySpellLang()<CR>
imap <F7> <C-o>:call MySpellLang()<CR
" >>

" slime <<
Plug 'jpalardy/vim-slime'
let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": "1"}
" >>

" text obj <<
Plug 'reedes/vim-textobj-quote'
Plug 'kana/vim-textobj-user'
Plug 'kana/vim-textobj-line'
Plug 'kana/vim-textobj-entire'

let g:expand_region_text_objects = {
\ 'iw'  :0,
\ 'iW'  :0,
\ 'i"'  :0,
\ 'i''' :0,
\ 'i)'  :1,
\ 'i]'  :1,
\ 'i}'  :1,
\ 'is'  :1,
\ 'ip'  :0,
\ 'ie'  :0,
\ }


" quotes
function! Quotes ()
  call textobj#quote#init()
endfunction

let g:textobj#quote#matchit = 1
" >>

" easy motion <<
Plug 'easymotion/vim-easymotion'
let g:EasyMotion_do_mapping = 0

nmap s <Plug>(easymotion-overwin-w)
" >>

" completion <<
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-go', { 'do': 'make'}
Plug 'Shougo/echodoc'

let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#go#pointer = 1

set completeopt+=noinsert
set completeopt-=preview
 >>

call plug#end()

" vim: fdm=marker foldmarker=<<,>>
