#!/usr/bin/env sh

# set config home
if [ -z "$XDG_CONFIG_HOME" ]; then
  echo '$XDG_CONFIG_HOME not set, falling back to `~/.config`'
  export XDG_CONFIG_HOME="$HOME/.config"
fi

# set caceh path
if [ -z "$XDG_CACHE_HOME" ]; then
  echo '$XDG_CACHE_HOME not set, falling back to `~/.cache`'
  export XDG_CACHE_HOME="$HOME/.cache"
fi

# run global install script first
sh "$XDG_CONFIG_HOME/install"

# install homerun things
sh "$XDG_CONFIG_HOME/homerun/lib/install"

# intialize cache dir
mkdir "$XDG_CACHE_HOME"

# vim: ft=zsh
